### ISSUE TITLE
Debian 'experimental'

### ISSUE THREAD

**Issue by jeroen** [r-hub/rhub-linux-builders#19]
I am also getting angry emails now Debian when stuff breaks in "experimental": https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828529. 

Would be nice if I can test on Debian experimental, in this case to test against [libssl1.1.0](https://packages.debian.org/experimental/libssl-dev) which is not yet in Debian unstable or testing.

It would suffice here to test with stock `r-base-dev` because that is usually very recent R-devel.

**Comment by gaborcsardi** [comment]
OK, here is the thing. I want to deploy the caching of binaries soon. But I don't want to build binaries for all Linux platforms, especially if you add them at this pace. :)

So I am thinking about two changes, mainly organizational:
1. installing multiple R versions on the same Docker image. So that we don't have to have so many images, and
2. having first tier and second tier platforms. I'll build/cache binary packages for first tier platforms only.

Sorry, this is not specifically related to this issue, just wanted to let you know. PRs for Docker images are welcome. (Btw. you can run Docker "natively" on macOS, this makes it easier to create the containers on your laptop.)

**Comment by jeroen** [comment]
I warned you I was going to add at least 20 systems :) A second tier of "community maintained" images sounds fine to me.

What exactly are you caching? The docker image? Perhaps You could consider a design with custom images so we can run the build in an arbitrary dockerhub image?

**Comment by gaborcsardi** [comment]
Not really caching, I'll just build binaries for all CRAN packages with compiled code, and use them to install dependencies. I cannot really cache containers, we don't have "projects".

**Comment by jeroen** [comment]
Is that a good idea? How do you invalidate when dependencies or system libraries change upstream?

**Comment by gaborcsardi** [comment]
I kind of need it, otherwise everything is very slow, especially revdep checks.

I'll only do it for stable platforms, i.e. not for Debian testing. There system libs do not change often. When I upgrade the system, I'll rebuild the cache. There will be an option to (re-)build all deps from source, in case sg goes wrong.

**Comment by gaborcsardi** [comment]
PRs are welcome!

**Comment by gaborcsardi** [comment]
Please reopen if you want to submit one.
